#!/usr/bin/env bash

FOREVER=./node_modules/.bin/forever
SERVER=./public/dist/server

start() {
  $FOREVER start $SERVER/worker.js
  $FOREVER start $SERVER/index.js
}

stop() {
  $FOREVER stopall
}

[ $1 == "start" ] && start
[ $1 == "stop" ] && stop
