#!/usr/bin/env bash

run() {
  local FOREVER="./node_modules/.bin/forever"
  local SERVER="./public/server"

  start() {
    $FOREVER start $SERVER/worker.js
    $FOREVER start $SERVER/index.js
  }

  stop() {
    $FOREVER stopall
  }

  [ "$1" == "start" ] && start
  [ "$1" == "stop" ] && stop
}

run $1
